name: runtests

on: [push, pull_request]

jobs:
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.0', '1.1', '1.2', '1.3', '1.4', '1.5', '1.6', '1.7-nightly']
        os: [ubuntu-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v1.0.0
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-runtest@master
        timeout-minutes: 20
        continue-on-error: ${{ matrix.julia-version == '1.7-nightly' }}
